### ISSUE TITLE
Turn Off Message Pushes to Blink-Staging from Puck Thor/Staging

### ISSUE THREAD

**Issue by sheyd** [DoSomething/puck#14]
### Current Behavior
What is the current behavior?

Puck Thor/Staging pushes events to `blink-staging` environment, and hence, messages into `blink-staging` Quasar queue.

### Expected Behavior

No Puck messages or events should push to `blink-staging` unless specified and coordinated with Team Storm.

#### Additional Information
This is currently a small blocker for fully testing Rogue push events to Quasar in staging environment.
Pivotal ID: [#154934157](https://www.pivotaltracker.com/story/show/154933744)

Hacky code exists to bypass this, but would like to not have extraneous logic built in to current Quasar code as it might introduce bugs into prod.

**Comment by mendelB** [comment]
@sheyd I checked out Puck prod on Heroku, and it seems like the [ENV variable 'flag'](https://github.com/DoSomething/puck/blob/master/lib/blink.js#L20) was indeed just removing the `BLINK_API_KEY` on Heroku. So I did the same for staging, and hopefully, the message pushes have stopped.

Mind just confirming that's indeed the case when you have the chance?

**Comment by sheyd** [comment]
Awesome, thanks @mendelB! I just purged the `blink-staging` Quasar queue of events, and will let you know if any more pop-up in its place.

**Comment by sheyd** [comment]
I've poked around Thor, and no new events are streaming in. Thanks for taking this on so quickly @mendelB!!! Marked solved and closing.
