### ISSUE TITLE
Missing Events / 404 Errors

### ISSUE THREAD

**Issue by mendelB** [DoSomething/puck#17]
## What's The Deal
We saw some discrepancies across Puck events (Facebook completed share events) being [tracked in Phoenix](https://github.com/DoSomething/phoenix-next/blob/master/resources/assets/components/actions/ShareAction/ShareAction.js#L84), from the posts it was simultaneously [sending over to Rogue](https://github.com/DoSomething/phoenix-next/blob/master/resources/assets/components/actions/ShareAction/ShareAction.js#L81). The Rogue totals were quite more than the Puck totals.

After diving into the Puck DB, and cross querying the Rogue posts with all the available corresponding Puck events — it definitely seems that there are many Puck events point blank missing from the database.

The Puck prod Papertrail log https://papertrailapp.com/systems/puck-production/events seems to show a pretty fair amount of `400`s for the past while (both GET - probably ping-keep-connection-alive events, and POSTs - actual event requests). This might definitely account for missing events though this would also mean this issue presumably extends across all event types :cold_sweat:

I’ve been poking around trying to figure out what might cause so many `400`s, but beyond the simple idea that this might have to do with increased traffic and server load, I can’t think of why this is happening. (I’ve seen some talk regarding `400`’s stemming from multiple dynos and mismatched Socket Ids, but we only have one Dyno activated on the Heroku app)

I managed to replicate locally once in a long inactive dosomething page, where I had some `400` unrecognized socket ID errors (so maybe at least some of these have to do with expired socket IDs).

Another straw I grasped which could also be related to the above - was the fact that over in Phoenix we instantiate a new Puck Client for every analytics event tracked (https://git.io/fhGjg) which causes many overlapping intervals to be set to keep pinging the server (https://git.io/fhGjV) but not sure if that would cause any issues necessarily.

One definite thing we can start doing is using the acknowledgement callback function https://socket.io/docs/#Sending-and-getting-data-acknowledgements Socket.io allows on emitted events to see if requests are failing (the `data` parameter would be `null` in such a case.) which we can then send to Papertrail with more data so we can at least start to know which events on which browsers are failing etc.

**Comment by weerd** [comment]
> Another straw I grasped which could also be related to the above - was the fact that over in Phoenix we instantiate a new Puck Client for every analytics event tracked (https://git.io/fhGjg) which causes many overlapping intervals to be set to keep pinging the server (https://git.io/fhGjV) but not sure if that would cause any issues necessarily.

We could definitely handle this better, and maybe use the same approach we used with the Sixpack helper that only instantiates a new client if none already exists:
https://github.com/DoSomething/phoenix-next/blob/master/resources/assets/helpers/index.js#L765

**Comment by weerd** [comment]
> One definite thing we can start doing is using the acknowledgement callback function https://socket.io/docs/#Sending-and-getting-data-acknowledgements Socket.io allows on emitted events to see if requests are failing (the data parameter would be null in such a case.) which we can then send to Papertrail with more data so we can at least start to know which events on which browsers are failing etc.

This makes sense as something we should do and log if there's issues.

**Comment by mendelB** [comment]
Ok, def! So I guess priority would be the acknowledgment callback in Puck, and then we can refactor the client instantiation in Phoenix?

**Comment by weerd** [comment]
> Ok, def! So I guess priority would be the acknowledgment callback in Puck, and then we can refactor the client instantiation in Phoenix?

Ya, or divide and conquer. Lets start by making some issues in PT of what's needed. Mind tackling the issue creation?

**Comment by mendelB** [comment]
> One definite thing we can start doing is using the acknowledgment callback function https://socket.io/docs/#Sending-and-getting-data-acknowledgements Socket.io allows on emitted events to see if requests are failing (the data parameter would be null in such a case.)

It seems I was quite wrong about this callback, it wouldn't be helpful to us on its own since it won't be invoked for failed events at all.

There are two alternatives I was able to find:

1) We can add a [`connect_error` listener](https://socket.io/docs/client-api/#Event-%E2%80%98connect-error%E2%80%99-1) to the Socket which when invoked would trigger the client set callback. 

While we're at it we could go about adding `connect_timeout` and `error` event listeners as well which'd do the same (perhaps passing the invoked event name to the callback?)

2) Another way would be to use [this timeout hack](https://stackoverflow.com/a/38542166/5657278) - where essentially based on whether we get acknowledgment from the server, we clear a timeout set up to trigger the error callback.


I guess way 1 is less hacky and uses documented events, but way 2 does give us more control over the data we can report.

**Comment by weerd** [comment]
I think I prefer option `#1` and just knowing that something went wrong. If we pass the invoked event name to the callback like you mentioned, that could also be useful and provide some insight on if it was a connection error or it was taking to long and timed out 🤔

**Comment by mendelB** [comment]
Ok, yeah that definitely feels safer and more reliable! Will do! (unfortunately, it's hard to replicate, or even know the specific error we're currently getting from clients to test that this will work properly, but if the Socket.io documentation is worth its salt, and based on some manual testing I did locally, this should do the trick for us!)

**Comment by mendelB** [comment]
Closing this out since we've since opted to move forward with Snowplow integration https://github.com/DoSomething/phoenix-next/pull/1455 in favor of the Puck system which has been deprecated https://github.com/DoSomething/phoenix-next/pull/1837
